const FETCH_TABLE = "FETCH_TABLE";
const FETCH_TABLE_SUCCESS = "FETCH_TABLE_SUCCESS";
const FETCH_TABLE_FAILED = "FETCH_TABLE_FAILED";

const FETCH_FAQ = "FETCH_FAQ";
const FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
const FETCH_FAQ_FAILED = "FETCH_FAQ_FAILED";

const FETCH_ADDTICKET = "FETCH_ADDTICKET";
const FETCH_ADDTICKET_SUCCESS = "FETCH_ADDTICKET_SUCCESS";
const FETCH_ADDTICKET_FAILED = "FETCH_ADDTICKET_FAILED";

const FETCH_SUMTABLE = "FETCH_SUMTABLE";
const FETCH_SUMTABLE_SUCCESS = "FETCH_SUMTABLE_SUCCESS";
const FETCH_SUMTABLE_FAILED = "FETCH_SUMTABLE_FAILED";

const ADD_SUPPORT_TICKET = "ADD_SUPPORT_TICKET";
const ADDED_SUPPORT_TICKET = "ADDED_SUPPORT_TICKET";

const FETCH_TICKET = "FETCH_TICKET";
const FETCH_TICKET_SUCCESS = "FETCH_TICKET_SUCCESS";
const FETCH_TICKET_FAILED = "FETCH_TICKET_FAILED";

const CLOSE_SUPPORT_TICKET = "CLOSE_SUPPORT_TICKET";
const CLOSED_SUPPORT_TICKET = "CLOSED_SUPPORT_TICKET";

const FETCH_CONTACT = "FETCH_CONTACT";
const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
const FETCH_CONTACT_FAILED = "FETCH_CONTACT_FAILED";

const FETCH_TICKETPICKER = "FETCH_TICKETPICKER";
const FETCH_TICKETPICKER_SUCCESS = "FETCH_TICKETPICKER_SUCCESS";
const FETCH_TICKETPICKER_FAILED = "FETCH_TICKETPICKER_FAILED";

const COURSE_REGISTER = "COURSE_REGISTER";
const COURSE_REGISTERED = "COURSE_REGISTERED";

const COURSE_CANCEL_COUPON = "COURSE_CANCEL_COUPON";
const COURSE_CANCELED_COUPON = "COURSE_CANCELED_COUPON";

const COURSE_REGISTER_COUPON = "COURSE_REGISTER_COUPON";
const COURSE_REGISTERED_COUPON = "COURSE_REGISTERED_COUPON";

const FETCH_ATICKCONTPRODEDITOR = "FETCH_ATICKCONTPRODEDITOR";
const FETCH_ATICKCONTPRODEDITOR_SUCCESS = "FETCH_ATICKCONTPRODEDITOR_SUCCESS";
const FETCH_ATICKCONTPRODEDITOR_FAILED = "FETCH_ATICKCONTPRODEDITOR_FAILED";

const FETCH_VOUCHERDETAIL = "FETCH_VOUCHERDETAIL";
const FETCH_VOUCHERDETAIL_SUCCESS = "FETCH_VOUCHERDETAIL_SUCCESS";
const FETCH_VOUCHERDETAIL_FAILED = "FETCH_VOUCHERDETAIL_FAILED";

const FETCH_MODAL = "FETCH_MODAL";
const FETCH_MODAL_SUCCESS = "FETCH_MODAL_SUCCESS";
const FETCH_MODAL_FAILED = "FETCH_MODAL_FAILED";

const STUDENT_CHANGE = "STUDENT_CHANGE";
const STUDENT_CHANGED = "STUDENT_CHANGED";

const VOUCHER_OWNER_CHANGE = "VOUCHER_OWNER_CHANGE";
const VOUCHER_OWNER_CHANGED = "VOUCHER_OWNER_CHANGED";

const NO_EMAIL = "NO_EMAIL";
const EMAIL_EXIST = "EMAIL_EXIST";
const NO_COUPON = "NO_COUPON";
const COUPON_EXIST = "COUPON_EXIST";
const COUPON_USED = "COUPON_USED";
const COUPON_INVALID = "COUPON_INVALID";
const POST_LOADER = "POST_LOADER";

export default {
	FETCH_TABLE,
	FETCH_TABLE_SUCCESS,
	FETCH_TABLE_FAILED,
	FETCH_FAQ,
	FETCH_FAQ_SUCCESS,
	FETCH_FAQ_FAILED,
	FETCH_ADDTICKET,
	FETCH_ADDTICKET_SUCCESS,
	FETCH_ADDTICKET_FAILED,
	ADD_SUPPORT_TICKET,
	ADDED_SUPPORT_TICKET,
	FETCH_SUMTABLE,
	FETCH_SUMTABLE_SUCCESS,
	FETCH_SUMTABLE_FAILED,
	FETCH_TICKET,
	FETCH_TICKET_SUCCESS,
	FETCH_TICKET_FAILED,
	CLOSE_SUPPORT_TICKET,
	CLOSED_SUPPORT_TICKET,
	FETCH_CONTACT,
	FETCH_CONTACT_SUCCESS,
	FETCH_CONTACT_FAILED,
	FETCH_TICKETPICKER,
	FETCH_TICKETPICKER_SUCCESS,
	FETCH_TICKETPICKER_FAILED,
	COURSE_REGISTER,
	COURSE_REGISTERED,
	COURSE_CANCEL_COUPON,
	COURSE_CANCELED_COUPON,
	COURSE_REGISTER_COUPON,
	COURSE_REGISTERED_COUPON,
	FETCH_ATICKCONTPRODEDITOR,
	FETCH_ATICKCONTPRODEDITOR_SUCCESS,
	FETCH_ATICKCONTPRODEDITOR_FAILED,
	FETCH_VOUCHERDETAIL,
	FETCH_VOUCHERDETAIL_SUCCESS,
	FETCH_VOUCHERDETAIL_FAILED,
	FETCH_MODAL,
	FETCH_MODAL_SUCCESS,
	FETCH_MODAL_FAILED,
	STUDENT_CHANGE,
	STUDENT_CHANGED,
	VOUCHER_OWNER_CHANGE,
	VOUCHER_OWNER_CHANGED,
	NO_EMAIL,
	EMAIL_EXIST,
	NO_COUPON,
	COUPON_EXIST,
	COUPON_USED,
	COUPON_INVALID,
	POST_LOADER
};