export const REFRESH_TABLE = "REFRESH_TABLE";
export const REFRESH_FAQ = "REFRESH_FAQ";
export const REFRESH_ADDTICKET = "REFRESH_ADDTICKET";
export const GET_TICKET = "GET_TICKET";
export const GET_CONTACT = "GET_CONTACT";
export const REFRESH_TICKETPICKER = "REFRESH_TICKETPICKER";