"use strict";

Object.defineProperty(exports, "__esModule", {
	value: true
});
var FETCH_TABLE = "FETCH_TABLE";
var FETCH_TABLE_SUCCESS = "FETCH_TABLE_SUCCESS";
var FETCH_TABLE_FAILED = "FETCH_TABLE_FAILED";

var FETCH_FAQ = "FETCH_FAQ";
var FETCH_FAQ_SUCCESS = "FETCH_FAQ_SUCCESS";
var FETCH_FAQ_FAILED = "FETCH_FAQ_FAILED";

var FETCH_ADDTICKET = "FETCH_ADDTICKET";
var FETCH_ADDTICKET_SUCCESS = "FETCH_ADDTICKET_SUCCESS";
var FETCH_ADDTICKET_FAILED = "FETCH_ADDTICKET_FAILED";

var FETCH_SUMTABLE = "FETCH_SUMTABLE";
var FETCH_SUMTABLE_SUCCESS = "FETCH_SUMTABLE_SUCCESS";
var FETCH_SUMTABLE_FAILED = "FETCH_SUMTABLE_FAILED";

var ADD_SUPPORT_TICKET = "ADD_SUPPORT_TICKET";
var ADDED_SUPPORT_TICKET = "ADDED_SUPPORT_TICKET";

var FETCH_TICKET = "FETCH_TICKET";
var FETCH_TICKET_SUCCESS = "FETCH_TICKET_SUCCESS";
var FETCH_TICKET_FAILED = "FETCH_TICKET_FAILED";

var CLOSE_SUPPORT_TICKET = "CLOSE_SUPPORT_TICKET";
var CLOSED_SUPPORT_TICKET = "CLOSED_SUPPORT_TICKET";

var FETCH_CONTACT = "FETCH_CONTACT";
var FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
var FETCH_CONTACT_FAILED = "FETCH_CONTACT_FAILED";

var FETCH_TICKETPICKER = "FETCH_TICKETPICKER";
var FETCH_TICKETPICKER_SUCCESS = "FETCH_TICKETPICKER_SUCCESS";
var FETCH_TICKETPICKER_FAILED = "FETCH_TICKETPICKER_FAILED";

var COURSE_REGISTER = "COURSE_REGISTER";
var COURSE_REGISTERED = "COURSE_REGISTERED";

var COURSE_CANCEL_COUPON = "COURSE_CANCEL_COUPON";
var COURSE_CANCELED_COUPON = "COURSE_CANCELED_COUPON";

var COURSE_REGISTER_COUPON = "COURSE_REGISTER_COUPON";
var COURSE_REGISTERED_COUPON = "COURSE_REGISTERED_COUPON";

var FETCH_ATICKCONTPRODEDITOR = "FETCH_ATICKCONTPRODEDITOR";
var FETCH_ATICKCONTPRODEDITOR_SUCCESS = "FETCH_ATICKCONTPRODEDITOR_SUCCESS";
var FETCH_ATICKCONTPRODEDITOR_FAILED = "FETCH_ATICKCONTPRODEDITOR_FAILED";

var FETCH_VOUCHERDETAIL = "FETCH_VOUCHERDETAIL";
var FETCH_VOUCHERDETAIL_SUCCESS = "FETCH_VOUCHERDETAIL_SUCCESS";
var FETCH_VOUCHERDETAIL_FAILED = "FETCH_VOUCHERDETAIL_FAILED";

var FETCH_MODAL = "FETCH_MODAL";
var FETCH_MODAL_SUCCESS = "FETCH_MODAL_SUCCESS";
var FETCH_MODAL_FAILED = "FETCH_MODAL_FAILED";

var STUDENT_CHANGE = "STUDENT_CHANGE";
var STUDENT_CHANGED = "STUDENT_CHANGED";

var VOUCHER_OWNER_CHANGE = "VOUCHER_OWNER_CHANGE";
var VOUCHER_OWNER_CHANGED = "VOUCHER_OWNER_CHANGED";

var NO_EMAIL = "NO_EMAIL";
var EMAIL_EXIST = "EMAIL_EXIST";
var NO_COUPON = "NO_COUPON";
var COUPON_EXIST = "COUPON_EXIST";
var COUPON_USED = "COUPON_USED";
var COUPON_INVALID = "COUPON_INVALID";
var POST_LOADER = "POST_LOADER";

exports.default = {
	FETCH_TABLE: FETCH_TABLE,
	FETCH_TABLE_SUCCESS: FETCH_TABLE_SUCCESS,
	FETCH_TABLE_FAILED: FETCH_TABLE_FAILED,
	FETCH_FAQ: FETCH_FAQ,
	FETCH_FAQ_SUCCESS: FETCH_FAQ_SUCCESS,
	FETCH_FAQ_FAILED: FETCH_FAQ_FAILED,
	FETCH_ADDTICKET: FETCH_ADDTICKET,
	FETCH_ADDTICKET_SUCCESS: FETCH_ADDTICKET_SUCCESS,
	FETCH_ADDTICKET_FAILED: FETCH_ADDTICKET_FAILED,
	ADD_SUPPORT_TICKET: ADD_SUPPORT_TICKET,
	ADDED_SUPPORT_TICKET: ADDED_SUPPORT_TICKET,
	FETCH_SUMTABLE: FETCH_SUMTABLE,
	FETCH_SUMTABLE_SUCCESS: FETCH_SUMTABLE_SUCCESS,
	FETCH_SUMTABLE_FAILED: FETCH_SUMTABLE_FAILED,
	FETCH_TICKET: FETCH_TICKET,
	FETCH_TICKET_SUCCESS: FETCH_TICKET_SUCCESS,
	FETCH_TICKET_FAILED: FETCH_TICKET_FAILED,
	CLOSE_SUPPORT_TICKET: CLOSE_SUPPORT_TICKET,
	CLOSED_SUPPORT_TICKET: CLOSED_SUPPORT_TICKET,
	FETCH_CONTACT: FETCH_CONTACT,
	FETCH_CONTACT_SUCCESS: FETCH_CONTACT_SUCCESS,
	FETCH_CONTACT_FAILED: FETCH_CONTACT_FAILED,
	FETCH_TICKETPICKER: FETCH_TICKETPICKER,
	FETCH_TICKETPICKER_SUCCESS: FETCH_TICKETPICKER_SUCCESS,
	FETCH_TICKETPICKER_FAILED: FETCH_TICKETPICKER_FAILED,
	COURSE_REGISTER: COURSE_REGISTER,
	COURSE_REGISTERED: COURSE_REGISTERED,
	COURSE_CANCEL_COUPON: COURSE_CANCEL_COUPON,
	COURSE_CANCELED_COUPON: COURSE_CANCELED_COUPON,
	COURSE_REGISTER_COUPON: COURSE_REGISTER_COUPON,
	COURSE_REGISTERED_COUPON: COURSE_REGISTERED_COUPON,
	FETCH_ATICKCONTPRODEDITOR: FETCH_ATICKCONTPRODEDITOR,
	FETCH_ATICKCONTPRODEDITOR_SUCCESS: FETCH_ATICKCONTPRODEDITOR_SUCCESS,
	FETCH_ATICKCONTPRODEDITOR_FAILED: FETCH_ATICKCONTPRODEDITOR_FAILED,
	FETCH_VOUCHERDETAIL: FETCH_VOUCHERDETAIL,
	FETCH_VOUCHERDETAIL_SUCCESS: FETCH_VOUCHERDETAIL_SUCCESS,
	FETCH_VOUCHERDETAIL_FAILED: FETCH_VOUCHERDETAIL_FAILED,
	FETCH_MODAL: FETCH_MODAL,
	FETCH_MODAL_SUCCESS: FETCH_MODAL_SUCCESS,
	FETCH_MODAL_FAILED: FETCH_MODAL_FAILED,
	STUDENT_CHANGE: STUDENT_CHANGE,
	STUDENT_CHANGED: STUDENT_CHANGED,
	VOUCHER_OWNER_CHANGE: VOUCHER_OWNER_CHANGE,
	VOUCHER_OWNER_CHANGED: VOUCHER_OWNER_CHANGED,
	NO_EMAIL: NO_EMAIL,
	EMAIL_EXIST: EMAIL_EXIST,
	NO_COUPON: NO_COUPON,
	COUPON_EXIST: COUPON_EXIST,
	COUPON_USED: COUPON_USED,
	COUPON_INVALID: COUPON_INVALID,
	POST_LOADER: POST_LOADER
};